#!/bin/bash
#$ -N bo_C_r2_array
#$ -q long
#$ -cwd
#$ -t 1-8
#$ -r n

# Generated by campaign/make_batches.py (prompt 30) — regenerate rather
# than hand-edit. Submitted by this wave's submit_this.sh (never by hand).

set -euo pipefail

GUROBI_MODULE="gurobi"

WAVE_DIR="$PWD"
TRIAL_DIR="$(cd "$PWD/../../.." && pwd)"
mkdir -p "$WAVE_DIR/runs"

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate PCM0826
module load "$GUROBI_MODULE"

eval "$(python "$TRIAL_DIR/campaign/get_row.py" "$SGE_TASK_ID" "$WAVE_DIR/design_matrix.csv")"

python "$TRIAL_DIR/multi_pem/multi_PEM_PCM.py" \
    --index "$INDEX" \
    --num_days "$NUM_DAYS" \
    --start_date "$START_DATE" \
    --output_directory "$WAVE_DIR/runs/run" \
    --retrofit_gen_dict "$(cat "$WAVE_DIR/retrofit_gen_dict_${INDEX}.json")"
