#!/bin/bash
# stage2_C_n0b — submit array + chained collector (prompt 27 n0b top-up).
# Run ON CRC from INSIDE this wave directory:  bash submit_this.sh
# Generated by campaign/make_batches.py — regenerate rather than hand-edit.

set -euo pipefail

WAVE_DIR="$PWD"
TRIAL_DIR="$(cd "$PWD/../../.." && pwd)"
REPO_DIR="$(cd "$TRIAL_DIR/.." && pwd)"

BRANCH="$(git -C "$REPO_DIR" branch --show-current)"
[[ "$BRANCH" == "d6" ]] || { echo "ABORT: repo on '$BRANCH', expected d6"; exit 1; }
git -C "$REPO_DIR" pull --rebase --autostash origin d6

J=$(qsub -terse -t 1-16 stage2_C_n0b_array.sh | cut -d. -f1)
[[ "$J" =~ ^[0-9]+$ ]] || { echo "BAD JID: $J"; exit 1; }
echo "stage2_C_n0b array submitted: J=$J (16 tasks, no -tc)"
qsub -hold_jid "$J" -cwd -M ylu28@nd.edu -m ea collect_stage2_C_n0b.sh
echo "collector submitted (holds on $J only — never on other waves)"
qstat -u ylu28
