#!/bin/bash
#$ -N collect_bo_C_r1
#$ -q long
#$ -cwd
#$ -r n

# Chained collector for bo_C_r1 (prompt 30; single-wave, bo-bot identity,
# 5-retry randomized-backoff push). Generated by campaign/make_batches.py.
# Submitted by submit_this.sh with -hold_jid on THIS wave's array only.

set -euo pipefail

WAVE_DIR="$PWD"
TRIAL_DIR="$(cd "$PWD/../../.." && pwd)"

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate PCM0826
export PYTHONNOUSERSITE=1  # ~/.local shadowing hazard (house-proven)

CAMPAIGN_DIR="$(cd "$WAVE_DIR/../.." && pwd)"
REPO_DIR="$(cd "$TRIAL_DIR/.." && pwd)"

BOT=(-c user.name="bo-bot" -c user.email="bo-bot@noreply.github.com")

push_with_retries() {
    local attempt
    for attempt in 1 2 3 4 5; do
        if git -C "$REPO_DIR" push origin d6; then
            return 0
        fi
        echo "push rejected (attempt $attempt/5) — rebase and retry"
        sleep $((30 + RANDOM % 60))
        git -C "$REPO_DIR" pull --rebase --autostash origin d6
    done
    git -C "$REPO_DIR" push origin d6 || {
        echo "PUSH FAILED after 5 retries:"
        git -C "$REPO_DIR" status
        exit 1
    }
}

missing=$(python - "$WAVE_DIR" <<'EOF'
import sys, csv, os
wdir = sys.argv[1]
with open(os.path.join(wdir, "design_matrix.csv"), newline="") as f:
    idx = [int(row["index"]) for row in csv.DictReader(f)]
missing = [i for i in idx
           if not os.path.isfile(os.path.join(
               wdir, "runs", f"run_index_{i}", "overall_simulation_output.csv"))]
print(" ".join(str(i) for i in missing))
EOF
)
if [[ -n "$missing" ]]; then
    marker="$WAVE_DIR/FAILED_bo_C_r1.md"
    {
        echo "# FAILED — bo_C_r1 incomplete at collection"
        echo
        echo "Missing run indices: $missing"
        echo
        echo "The chained acquisition job will see this marker and stop the"
        echo "round (no proposals). Recovery: Kay diagnoses, resubmits the"
        echo "gap (qsub -t a-b bo_C_r1_array.sh), re-runs this collector,"
        echo "then qsubs acquire_job.sh per the WEDGED/FAILED recipe in"
        echo "ROUND_LOG.md. Generated $(date -u +%FT%TZ)."
    } > "$marker"
    git -C "$REPO_DIR" add -- "$marker"
    git -C "$REPO_DIR" "${BOT[@]}" commit -m "bo-bot: FAILED marker (bo_C_r1 incomplete)"
    push_with_retries
    echo "GATE FAIL: missing indices: $missing"
    exit 1
fi
echo "GATE PASS: bo_C_r1 complete"

python "$CAMPAIGN_DIR/summarize_wave.py" "$WAVE_DIR"

git -C "$REPO_DIR" add -- "$WAVE_DIR/objectives.csv" "$WAVE_DIR/site_detail.csv"
git -C "$REPO_DIR" "${BOT[@]}" commit -m "bo-bot: bo_C_r1 results"
push_with_retries
echo "collect_bo_C_r1 done"
