#!/bin/bash
# bo_C_r1 — submit the WHOLE round triple: array -> collector -> acquisition
# (prompt 30). Invocable from anywhere (block #1 for r1; acquire_job.sh for
# later rounds). Generated by campaign/make_batches.py.
cd "$(dirname "${BASH_SOURCE[0]}")"
set -euo pipefail

WAVE_DIR="$PWD"
TRIAL_DIR="$(cd "$PWD/../../.." && pwd)"
REPO_DIR="$(cd "$TRIAL_DIR/.." && pwd)"
BO_DIR="$TRIAL_DIR/campaign/analysis/bo_stage2"

BRANCH="$(git -C "$REPO_DIR" branch --show-current)"
[[ "$BRANCH" == "d6" ]] || { echo "ABORT: repo on '$BRANCH', expected d6"; exit 1; }
git -C "$REPO_DIR" pull --rebase --autostash origin d6

EMAIL=(-M ylu28@nd.edu -m ea)
mkdir -p "$BO_DIR/logs"

J=$(qsub -terse -t 1-8 "${EMAIL[@]}" bo_C_r1_array.sh | cut -d. -f1)
[[ "$J" =~ ^[0-9]+$ ]] || { echo "BAD ARRAY JID: $J"; exit 1; }
C=$(qsub -terse -hold_jid "$J" -cwd "${EMAIL[@]}" collect_bo_C_r1.sh)
[[ "$C" =~ ^[0-9]+$ ]] || { echo "BAD COLLECTOR JID: $C"; exit 1; }
A=$(qsub -terse -hold_jid "$C" -cwd -N acq_bo_C_r1 -v BO_ROUND=1 \
    -o "$BO_DIR/logs/" -e "$BO_DIR/logs/" "${EMAIL[@]}" \
    "$BO_DIR/acquire_job.sh")
[[ "$A" =~ ^[0-9]+$ ]] || { echo "BAD ACQ JID: $A"; exit 1; }

echo "SUBMITTED r1: array=$J collector=$C acq=$A" >> "$BO_DIR/ROUND_LOG.md"
BOT=(-c user.name="bo-bot" -c user.email="bo-bot@noreply.github.com")
git -C "$REPO_DIR" add -- "$BO_DIR/ROUND_LOG.md"
git -C "$REPO_DIR" "${BOT[@]}" commit -m "bo-bot: SUBMITTED r1 (array=$J collector=$C acq=$A)"
for attempt in 1 2 3 4 5; do
    git -C "$REPO_DIR" push origin d6 && break
    echo "push rejected (attempt $attempt/5) — rebase and retry"
    sleep $((30 + RANDOM % 60))
    git -C "$REPO_DIR" pull --rebase --autostash origin d6
    [[ "$attempt" == 5 ]] && { git -C "$REPO_DIR" push origin d6 || exit 1; }
done
echo "SUBMITTED r1: array=$J collector=$C acq=$A"
qstat -u ylu28 || true
