#!/bin/bash
#$ -N collect_pairgrid_tail_wind_303_C
#$ -q long
#$ -cwd

# Chained collector for pairgrid_tail_wind_303_C (prompt 28 T1; single-wave adaptation of the
# prompt-27 collector spec — see stage2_backfill_C/collect_stage2.sh).
# Submitted by submit_this.sh with -hold_jid on THIS wave's array only.
# Generated by campaign/make_batches.py — regenerate rather than hand-edit.
#
# Order of operations (deliberate):
#   1. integrity gate FIRST, self-contained (never resubmit_missing.py);
#   2. on any gap: FAILED_pairgrid_tail_wind_303_C.md marker, commit + push the marker ONLY;
#   3. on pass: summarize, bot-identity commit of explicit paths, commit
#      BEFORE pull --rebase, push with RETRY LOOP (up to 5 attempts,
#      randomized sleep — up to 4 concurrent bot pushers share d6, so the
#      stage2 retry-once is insufficient here).

set -euo pipefail

WAVE_DIR="$PWD"
TRIAL_DIR="$(cd "$PWD/../../.." && pwd)"

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate PCM0826

CAMPAIGN_DIR="$(cd "$WAVE_DIR/../.." && pwd)"
REPO_DIR="$(cd "$TRIAL_DIR/.." && pwd)"

BOT=(-c user.name="pairgrid-bot" -c user.email="pairgrid-bot@noreply.github.com")

push_with_retries() {
    local attempt
    for attempt in 1 2 3 4 5; do
        if git -C "$REPO_DIR" push origin d6; then
            return 0
        fi
        echo "push rejected (attempt $attempt/5) — rebase and retry"
        sleep $((30 + RANDOM % 60))
        git -C "$REPO_DIR" pull --rebase --autostash origin d6
    done
    if git -C "$REPO_DIR" push origin d6; then
        return 0
    fi
    echo "PUSH FAILED after 5 retries — stopping with status visible:"
    git -C "$REPO_DIR" status
    git -C "$REPO_DIR" log --oneline -3
    exit 1
}

# --- 1. integrity gate: sentinel count vs the design matrix itself ----------
missing=$(python - "$WAVE_DIR" <<'EOF'
import sys, csv, os
wdir = sys.argv[1]
with open(os.path.join(wdir, "design_matrix.csv"), newline="") as f:
    idx = [int(row["index"]) for row in csv.DictReader(f)]
missing = [i for i in idx
           if not os.path.isfile(os.path.join(
               wdir, "runs", f"run_index_{i}", "overall_simulation_output.csv"))]
print(" ".join(str(i) for i in missing))
EOF
)
if [[ -n "$missing" ]]; then
    marker="$WAVE_DIR/FAILED_pairgrid_tail_wind_303_C.md"
    {
        echo "# FAILED — pairgrid_tail_wind_303_C incomplete at collection"
        echo
        echo "Missing run indices (no overall_simulation_output.csv):"
        echo
        for i in $missing; do echo "- $i"; done
        echo
        echo "Recovery: Kay runs resubmit_missing.py (interactive) or a"
        echo "manual 'qsub -t a-b' per contiguous gap, then re-runs this"
        echo "collector. Generated $(date -u +%FT%TZ) by collect_pairgrid_tail_wind_303_C.sh."
    } > "$marker"
    git -C "$REPO_DIR" add -- "$marker"
    git -C "$REPO_DIR" "${BOT[@]}" commit -m "pairgrid-bot: FAILED marker (pairgrid_tail_wind_303_C incomplete)"
    push_with_retries
    echo "GATE FAIL: missing indices: $missing — marker pushed, no partial CSVs."
    exit 1
fi
echo "GATE PASS: pairgrid_tail_wind_303_C complete ($(ls -d "$WAVE_DIR"/runs/run_index_* | wc -l) run dirs)"

# --- 2. summarize this wave only --------------------------------------------
python "$CAMPAIGN_DIR/summarize_wave.py" "$WAVE_DIR"

# --- 3. bot commit (explicit paths only), commit BEFORE pull --rebase, push --
git -C "$REPO_DIR" add -- "$WAVE_DIR/objectives.csv" "$WAVE_DIR/site_detail.csv"
git -C "$REPO_DIR" "${BOT[@]}" commit -m "pairgrid-bot: pairgrid_tail_wind_303_C results"
push_with_retries
echo "collect_pairgrid_tail_wind_303_C done: objectives pushed"
