#!/bin/bash
#$ -N pilot_array
#$ -q long
#$ -cwd
#$ -t 1-12
#$ -tc 20

# Generated by campaign/submit_array.py — regenerate rather than hand-edit.
# Submit from INSIDE the wave directory:
#   cd <wave_dir> && qsub pilot_array.sh
# (#$ -cwd runs each task there; all paths below derive from $PWD so this
#  committed script runs on CRC unchanged.)

set -euo pipefail

# Deliberate (doc 14 §5.1 deviation, see README): the prescient options and
# this module pin live here in the version-controlled script, not in
# manifest.json.
GUROBI_MODULE="gurobi/11.0.2"

WAVE_DIR="$PWD"
TRIAL_DIR="$(cd "$PWD/../../.." && pwd)"
mkdir -p "$WAVE_DIR/runs"

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate PCM0826
module load "$GUROBI_MODULE"

# design_matrix.csv `index` == $SGE_TASK_ID (both 1-based, 1:1 — no
# positional lookup). get_row.py prints ONLY scalar shell assignments.
eval "$(python "$TRIAL_DIR/campaign/get_row.py" "$SGE_TASK_ID" "$WAVE_DIR/design_matrix.csv")"

python "$TRIAL_DIR/multi_pem/multi_PEM_PCM.py" \
    --index "$INDEX" \
    --num_days "$NUM_DAYS" \
    --start_date "$START_DATE" \
    --output_directory "$WAVE_DIR/runs/run" \
    --retrofit_gen_dict "$(cat "$WAVE_DIR/retrofit_gen_dict_${INDEX}.json")"
