#!/bin/bash
# pairgrid_tail_wind_122_C — submit array + chained collector (prompt 28 T1).
# Run ON CRC from INSIDE this wave directory:  bash submit_this.sh
# Generated by campaign/make_batches.py — regenerate rather than hand-edit.

set -euo pipefail

WAVE_DIR="$PWD"
TRIAL_DIR="$(cd "$PWD/../../.." && pwd)"
REPO_DIR="$(cd "$TRIAL_DIR/.." && pwd)"

BRANCH="$(git -C "$REPO_DIR" branch --show-current)"
[[ "$BRANCH" == "d6" ]] || { echo "ABORT: repo on '$BRANCH', expected d6"; exit 1; }
git -C "$REPO_DIR" pull --rebase --autostash origin d6

J=$(qsub -terse -t 1-81 pairgrid_tail_wind_122_C_array.sh | cut -d. -f1)
[[ "$J" =~ ^[0-9]+$ ]] || { echo "BAD JID: $J"; exit 1; }
echo "pairgrid_tail_wind_122_C array submitted: J=$J (81 tasks, no -tc)"
qsub -hold_jid "$J" -cwd -M ylu28@nd.edu -m ea collect_pairgrid_tail_wind_122_C.sh
echo "collector submitted (holds on $J only — never on other waves)"
qstat -u ylu28
