"""Generate ONE SGE array-job script per wave (doc 14 §5.2). Never submits.

Usage:  python submit_array.py <wave_dir> [--max-concurrent 20]

Portability contract: the committed script must run on CRC unchanged, so it
contains NO local absolute paths. Kay submits it from INSIDE the wave dir;
with `#$ -cwd` every task runs there too, and the template derives all paths
from $PWD at runtime (waves/<wave> -> waves -> campaign -> trial_0826).
"""

import argparse
import os

import pandas as pd

TEMPLATE = """#!/bin/bash
#$ -N {wave_name}_array
#$ -q long
#$ -cwd
#$ -t 1-{n}
#$ -tc {max_concurrent}

# Generated by campaign/submit_array.py — regenerate rather than hand-edit.
# Submit from INSIDE the wave directory:
#   cd <wave_dir> && qsub {wave_name}_array.sh
# (#$ -cwd runs each task there; all paths below derive from $PWD so this
#  committed script runs on CRC unchanged.)

set -euo pipefail

# Pinned solver module. TODO(Kay): pin the exact CRC version once
# (`module avail gurobi`), e.g. GUROBI_MODULE="gurobi/11.0.3".
# Deliberate (doc 14 §5.1 deviation, see README): the prescient options and
# this module pin live here in the version-controlled script, not in
# manifest.json.
GUROBI_MODULE="gurobi"

WAVE_DIR="$PWD"
TRIAL_DIR="$(cd "$PWD/../../.." && pwd)"
mkdir -p "$WAVE_DIR/runs"

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate PCM0826
module load "$GUROBI_MODULE"

# design_matrix.csv `index` == $SGE_TASK_ID (both 1-based, 1:1 — no
# positional lookup). get_row.py prints ONLY scalar shell assignments.
eval "$(python "$TRIAL_DIR/campaign/get_row.py" "$SGE_TASK_ID" "$WAVE_DIR/design_matrix.csv")"

python "$TRIAL_DIR/multi_pem/multi_PEM_PCM.py" \\
    --index "$INDEX" \\
    --num_days "$NUM_DAYS" \\
    --start_date "$START_DATE" \\
    --output_directory "$WAVE_DIR/runs/run" \\
    --retrofit_gen_dict "$(cat "$WAVE_DIR/retrofit_gen_dict_${{INDEX}}.json")"
"""


def generate_script(wave_dir, max_concurrent=20):
    design = pd.read_csv(os.path.join(wave_dir, "design_matrix.csv"))
    indices = sorted(int(i) for i in design["index"])
    n = len(indices)
    assert indices == list(range(1, n + 1)), (
        f"design-matrix indices must form exactly 1..N, got {indices[:5]}...{indices[-5:]}"
    )
    wave_name = os.path.basename(os.path.normpath(wave_dir))
    script_path = os.path.join(wave_dir, f"{wave_name}_array.sh")
    with open(script_path, "w") as f:
        f.write(TEMPLATE.format(wave_name=wave_name, n=n, max_concurrent=max_concurrent))
    os.chmod(script_path, 0o755)
    return script_path


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("wave_dir")
    parser.add_argument("--max-concurrent", type=int, default=20,
                        help="#$ -tc value: fair-share / license concurrency cap")
    args = parser.parse_args(argv)
    print(generate_script(args.wave_dir, args.max_concurrent))


if __name__ == "__main__":
    main()
